# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - xvfb-run julia -e 'Pkg.clone(pwd()); using BinDeps; println(BinDeps.debug("BeetleWay")); Pkg.build("BeetleWay"); Pkg.test("BeetleWay"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BeetleWay")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("BeetleWay")); include(joinpath("docs", "make.jl"))'
