site_name:        BeetleWay.jl
repo_url:         https://github.com/yakir12/BeetleWay.jl
site_description: helps scientists log video files and the experiments associated with these files
site_author:      yakir12

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
